const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const money=n=>"₹"+Number(n).toLocaleString("en-IN");
const productById=id=>PRODUCTS.find(p=>p.id==id);
let cart=JSON.parse(localStorage.getItem("fc4_cart")||"[]");
let wishlist=JSON.parse(localStorage.getItem("fc4_wishlist")||"[]");
let orders=JSON.parse(localStorage.getItem("fc4_orders")||"[]");
let user=JSON.parse(localStorage.getItem("fc4_user")||"null");
let accounts=JSON.parse(localStorage.getItem("fc4_accounts")||"[]");
let addresses=JSON.parse(localStorage.getItem("fc4_addresses")||"[]");
let stock=JSON.parse(localStorage.getItem("fc4_stock")||"{}");
let coupon=localStorage.getItem("fc4_coupon")||"";
let lastSearches=JSON.parse(localStorage.getItem("fc4_searches")||"[]");

PRODUCTS.forEach(p=>{if(stock[p.id]===undefined)stock[p.id]=p.stock});
function save(){
 localStorage.setItem("fc4_cart",JSON.stringify(cart));
 localStorage.setItem("fc4_wishlist",JSON.stringify(wishlist));
 localStorage.setItem("fc4_orders",JSON.stringify(orders));
 localStorage.setItem("fc4_user",JSON.stringify(user));
 localStorage.setItem("fc4_accounts",JSON.stringify(accounts));
 localStorage.setItem("fc4_addresses",JSON.stringify(addresses));
 localStorage.setItem("fc4_stock",JSON.stringify(stock));
 localStorage.setItem("fc4_coupon",coupon);
 localStorage.setItem("fc4_searches",JSON.stringify(lastSearches));
}
const cartCount=()=>cart.reduce((s,x)=>s+x.qty,0);
const subtotal=()=>cart.reduce((s,x)=>s+productById(x.id).price*x.qty,0);
const discount=()=>coupon==="FRESH100"&&subtotal()>=499?100:coupon==="SAVE50"&&subtotal()>=299?50:0;
const delivery=()=>subtotal()===0?0:(subtotal()-discount()>=499?0:40);
const total=()=>Math.max(0,subtotal()-discount()+delivery());
const left=id=>Number(stock[id]||0);
const inWish=id=>wishlist.includes(Number(id));
function icon(n,cls=""){const m={
home:`<svg class="${cls}" viewBox="0 0 24 24"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1V10Z"/></svg>`,
shop:`<svg class="${cls}" viewBox="0 0 24 24"><path d="M3 5h18l-2 16H5L3 5Zm4 0a5 5 0 0 1 10 0M9 11h.01M15 11h.01"/></svg>`,
cart:`<svg class="${cls}" viewBox="0 0 24 24"><path d="M3 4h2l2.2 11.2a2 2 0 0 0 2 1.6h7.9a2 2 0 0 0 1.9-1.4L21 8H7M10 20h.01M17 20h.01"/></svg>`,
user:`<svg class="${cls}" viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21c.8-4 3.3-6 8-6s7.2 2 8 6"/></svg>`,
heart:`<svg class="${cls}" viewBox="0 0 24 24"><path d="M20.8 8.7c0 5.2-8.8 10.3-8.8 10.3S3.2 13.9 3.2 8.7A4.7 4.7 0 0 1 12 6.3a4.7 4.7 0 0 1 8.8 2.4Z"/></svg>`,
search:`<svg class="${cls}" viewBox="0 0 24 24"><circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 5 5"/></svg>`,
apple:`<svg class="${cls}" viewBox="0 0 24 24"><path d="M14 5c.8-1 1-2.2.9-3.3-1.2.1-2.5.8-3.2 1.7-.7.8-1.2 2.1-1 3.2 1.2.1 2.5-.6 3.3-1.6ZM20.5 17.1c-.6 1.3-.9 1.9-1.7 3-.9 1.2-2.2 2.7-3.8 2.7-1.4 0-1.8-.9-3.6-.9-1.8 0-2.2.9-3.6.9-1.6 0-2.8-1.3-3.7-2.5C1.6 16.8.3 10.2 3.5 7.1a4.9 4.9 0 0 1 3.7-1.9c1.5 0 2.9 1 3.7 1 0 0 1.9-1.1 3.9-1.1 2.2.1 3.5 1.1 4.4 2.1-3.9 2.2-3.2 7.7 1.3 9.9Z"/></svg>`,
leaf:`<svg class="${cls}" viewBox="0 0 24 24"><path d="M20 4C10 4 5 8 5 14c0 3 2 5 5 5 6 0 10-5 10-15ZM4 21c2-4 5-7 10-10"/></svg>`,
milk:`<svg class="${cls}" viewBox="0 0 24 24"><path d="M7 3h10M8 3v4l-2 4v10h12V11l-2-4V3M7 11h10M9 7h6"/></svg>`,
grain:`<svg class="${cls}" viewBox="0 0 24 24"><path d="M12 21V4M12 8C8 8 6 6 6 3c4 0 6 2 6 5Zm0 5c4 0 6-2 6-5-4 0-6 2-6 5Zm0 0c-4 0-6-2-6-5 4 0 6 2 6 5Z"/></svg>`,
snack:`<svg class="${cls}" viewBox="0 0 24 24"><path d="M5 5h14l-1 15H6L5 5Zm2 0 1-3h8l1 3M9 9h6M9 13h6"/></svg>`,
drink:`<svg class="${cls}" viewBox="0 0 24 24"><path d="M7 3h10l-1 18H8L7 3Zm3-2h4M9 8h6"/></svg>`,
care:`<svg class="${cls}" viewBox="0 0 24 24"><path d="M8 4h8l1 4H7l1-4Zm0 4h8l1 13H7L8 8Zm2-4V2h4v2"/></svg>`,
pin:`<svg class="${cls}" viewBox="0 0 24 24"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>`,
truck:`<svg class="${cls}" viewBox="0 0 24 24"><path d="M3 6h11v11H3zM14 10h4l3 3v4h-7zM7 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4ZM18 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/></svg>`,
check:`<svg class="${cls}" viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg>`,
close:`<svg class="${cls}" viewBox="0 0 24 24"><path d="m5 5 14 14M19 5 5 19"/></svg>`,
phone:`<svg class="${cls}" viewBox="0 0 24 24"><path d="M6 3h3l2 5-2 2c1 2 2 3 4 4l2-2 5 2v3c0 1-1 2-2 2C10 18 6 14 4 8c0-2 1-3 2-5Z"/></svg>`,
mail:`<svg class="${cls}" viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></svg>`,
shield:`<svg class="${cls}" viewBox="0 0 24 24"><path d="M12 3 20 6v5c0 5-3.2 8.5-8 10-4.8-1.5-8-5-8-10V6l8-3Z"/><path d="m8 12 3 3 5-6"/></svg>`
};return m[n]||""}
function nav(){
 return `<div class="announcement">Free delivery on orders above ₹499 <span>•</span> Fresh deals every day</div>
 <header class="header"><div class="nav">
 <a class="logo" href="#/"><b>Fresh</b><strong>Cart</strong></a>
 <nav><a href="#/" class="navlink">${icon("home")} Home</a><a href="#/shop" class="navlink">${icon("shop")} Shop</a>
 <div class="catwrap"><button class="navlink catbutton">Categories <span>⌄</span></button><div class="dropdown">${CATEGORIES.map(c=>`<a href="#/shop?cat=${encodeURIComponent(c.name)}">${icon(c.icon)} ${c.name}</a>`).join("")}</div></div>
 <a href="#/deals" class="navlink">Deals</a></nav>
 <form class="searchbox" onsubmit="event.preventDefault();searchGo(this.q.value)">${icon("search")}<input autocomplete="off" name="q" id="globalSearch" placeholder="Search for groceries, fruits, milk & more"><button>Search</button><div id="suggestions"></div></form>
 <div class="actions"><a href="#/wishlist" title="Wishlist" class="iconaction">${icon("heart")}<i>${wishlist.length}</i></a><a href="#/account" class="iconaction" title="Account">${icon("user")}</a><a href="#/orders" class="orderslink">Orders</a><a href="#/cart" class="iconaction" title="Cart">${icon("cart")}<i>${cartCount()}</i></a></div>
 </div></header>`;
}
function footer(){
 return `<footer><div class="footergrid"><div><a class="flogo" href="#/">Fresh<span>Cart</span></a><p>Fresh groceries and everyday essentials delivered to your doorstep with simple prices and convenient delivery.</p><div class="social">f　◎　▶　in</div></div><div><h4>Shop</h4><a href="#/shop">All Products</a>${CATEGORIES.slice(0,4).map(c=>`<a href="#/shop?cat=${encodeURIComponent(c.name)}">${c.name}</a>`).join("")}</div><div><h4>Customer Care</h4><a href="#/contact">Contact Us</a><a href="#/faq">FAQs</a><a href="#/orders">Track Order</a><a href="#/shipping">Shipping Policy</a><a href="#/returns">Refund Policy</a><a href="#/terms">Terms & Conditions</a><a href="#/privacy">Privacy Policy</a></div><div><h4>Get offers in your inbox</h4><p>Subscribe for grocery deals and new arrivals.</p><form onsubmit="subscribe(event)" class="subscribe"><input type="email" required placeholder="Your email address"><button>Subscribe</button></form><div class="payicons">VISA　UPI　COD</div></div></div><div class="copyright">© 2026 FreshCart. Front-end e-commerce project template.</div></footer>`;
}
function shell(content){document.querySelector("#app").innerHTML=nav()+content+footer();window.scrollTo({top:0,behavior:"smooth"});bindSearch()}
function bindSearch(){
 const input=$("#globalSearch"), box=$("#suggestions");if(!input)return;
 input.addEventListener("input",()=>{const q=input.value.trim().toLowerCase();if(!q){box.innerHTML="";box.style.display="none";return}const list=PRODUCTS.filter(p=>(p.name+" "+p.cat+" "+p.brand).toLowerCase().includes(q)).slice(0,6);box.innerHTML=list.map(p=>`<a href="#/product/${p.id}"><img src="${p.img}"><span><b>${p.name}</b><small>${p.cat} • ${money(p.price)}</small></span></a>`).join("")||`<div class="noresult">No matching products</div>`;box.style.display="block"});
 document.addEventListener("click",e=>{if(!e.target.closest(".searchbox"))box.style.display="none"},{once:true});
}
function searchGo(q){q=q.trim();if(!q)return;if(!lastSearches.includes(q))lastSearches.unshift(q);lastSearches=lastSearches.slice(0,5);save();location.hash="#/shop?search="+encodeURIComponent(q)}
function stockBadge(p){
 const s=left(p.id);
 if(s<=0)return `<span class="stock out">Out of stock</span>`;
 if(s<=3)return `<span class="stock low">Only ${s} left</span>`;
 return `<span class="stock ok">${s} in stock</span>`;
}
function card(p){
 const s=left(p.id), disabled=s<=0;
 return `<article class="card"><div class="pic"><a href="#/product/${p.id}"><img src="${p.img}" loading="lazy" alt="${p.name}"></a>${p.tag?`<span class="tag">${p.tag}</span>`:""}<button class="wish ${inWish(p.id)?"selected":""}" onclick="toggleWish(${p.id})" title="Wishlist">${icon("heart")}</button></div><div class="cardbody"><small>${p.brand} • ${p.unit}</small><a href="#/product/${p.id}"><h3>${p.name}</h3></a><div class="rating">★ ${p.rating} <span>(${p.reviews})</span></div><div><b class="price">${money(p.price)}</b><del>${money(p.old)}</del><span class="off">${Math.round((1-p.price/p.old)*100)}% OFF</span></div>${stockBadge(p)}<button class="add ${disabled?"disabled":""}" ${disabled?"disabled":""} onclick="add(${p.id})">${disabled?"Out of stock":"+ Add to cart"}</button></div></article>`;
}
function productRow(list,title,sub="",link="#/shop"){
 return `<section class="section container"><div class="sectionhead"><div><span class="eyebrow">${sub}</span><h2>${title}</h2></div><a class="viewall" href="${link}">View all →</a></div><div class="products">${list.map(card).join("")}</div></section>`;
}
function home(){
 const best=[...PRODUCTS].sort((a,b)=>b.rating-a.rating).slice(0,6);
 const deals=[...PRODUCTS].sort((a,b)=>(1-b.price/b.old)-(1-a.price/a.old)).slice(0,6);
 const newArr=PRODUCTS.slice(42,48);
 const brands=BRANDS.map((b,i)=>`<a href="#/shop?brand=${encodeURIComponent(b)}"><span>${String.fromCharCode(65+i)}</span><b>${b}</b><small>Shop products</small></a>`).join("");
 shell(`<main><section class="hero container"><div class="heroMain"><div class="heroText"><span class="pill">Same-day delivery available</span><h1>Fresh groceries for every day.</h1><p>Shop fruits, vegetables, dairy, pantry essentials, snacks and household products — all in one place.</p><div class="heroBtns"><a class="btn" href="#/shop">Shop groceries →</a><a class="btn outline" href="#/deals">View today's deals</a></div><div class="trust"><span>${icon("check")} Quality checked</span><span>${icon("check")} Easy returns</span><span>${icon("shield")} Secure checkout</span></div></div><img src="https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1100&q=85" alt="Fresh groceries"></div><div class="heroSide"><div class="deal green"><small>WEEKLY DEAL</small><h3>Up to 30% OFF</h3><p>Fresh fruits & vegetables</p><a href="#/shop?cat=Vegetables">Shop produce →</a></div><div class="deal orange"><small>WELCOME OFFER</small><h3>₹100 OFF</h3><p>On orders above ₹499</p><b>Use FRESH100</b></div></div></section>
 <section class="container benefits"><div>${icon("truck")}<b>Fast delivery</b><span>Convenient doorstep delivery</span></div><div>${icon("leaf")}<b>Fresh quality</b><span>Carefully selected products</span></div><div>${icon("shield")}<b>Secure payment</b><span>Protected checkout</span></div><div>${icon("phone")}<b>Customer support</b><span>We're here every day</span></div></section>
 <section class="container"><div class="sectionhead"><div><span class="eyebrow">Browse</span><h2>Shop by category</h2></div><a class="viewall" href="#/shop">View all →</a></div><div class="categories">${CATEGORIES.map(c=>`<a class="category" href="#/shop?cat=${encodeURIComponent(c.name)}">${icon(c.icon)}<b>${c.name}</b><small>${PRODUCTS.filter(p=>p.cat===c.name).length} products</small></a>`).join("")}</div></section>
 ${productRow(deals,"Deals of the Day","Limited-time savings","#/deals")}
 ${productRow(best,"Best Sellers","Popular with shoppers","#/shop?sort=rating")}
 <section class="promo container"><div><span class="eyebrow">FIRST ORDER</span><h2>Get ₹100 off your first grocery order</h2><p>Use code <b>FRESH100</b> at checkout on orders above ₹499.</p><a class="btn" href="#/shop">Start shopping</a></div><div class="promoart">₹100 OFF</div></section>
 ${productRow(newArr,"New Arrivals","Freshly added","#/shop?sort=new")}
 <section class="section container"><div class="sectionhead"><div><span class="eyebrow">Brands</span><h2>Shop popular brands</h2></div></div><div class="brands">${brands}</div></section>
 <section class="section container reviewsHome"><div class="sectionhead"><div><span class="eyebrow">Customer stories</span><h2>Loved by FreshCart shoppers</h2></div></div><div class="reviewgrid"><div><div class="stars">★★★★★</div><p>“The product selection is simple to browse and the fresh produce arrived in good condition.”</p><b>Priya R.</b><small>Verified customer</small></div><div><div class="stars">★★★★★</div><p>“I like seeing the stock quantity before adding products to my cart.”</p><b>Arun K.</b><small>Verified customer</small></div><div><div class="stars">★★★★☆</div><p>“Checkout is clear and the delivery fee is shown before placing the order.”</p><b>Meena S.</b><small>Verified customer</small></div></div></section>
 <section class="container why"><div><span class="eyebrow">Why FreshCart</span><h2>Everything you need for a simpler grocery run.</h2></div><div class="whygrid"><div>${icon("check")}<h3>Quality checked</h3><p>Products are presented with clear pack sizes, prices and stock.</p></div><div>${icon("truck")}<h3>Flexible delivery</h3><p>Choose a convenient delivery slot during checkout.</p></div><div>${icon("shield")}<h3>Secure checkout</h3><p>Review your complete total before placing an order.</p></div><div>${icon("heart")}<h3>Wishlist</h3><p>Save products you want to buy later.</p></div></div></section>
 </main>`);
}
function shop(){
 const u=new URLSearchParams(location.hash.split("?")[1]||"");
 const cat=u.get("cat")||"",brand=u.get("brand")||"",q=(u.get("search")||"").toLowerCase(),sort=u.get("sort")||"";
 let list=PRODUCTS.filter(p=>(!cat||p.cat===cat)&&(!brand||p.brand===brand)&&(!q||(p.name+" "+p.cat+" "+p.brand).toLowerCase().includes(q)));
 if(sort==="low")list.sort((a,b)=>a.price-b.price);if(sort==="high")list.sort((a,b)=>b.price-a.price);if(sort==="rating")list.sort((a,b)=>b.rating-a.rating);
 shell(`<main class="page container"><div class="breadcrumb"><a href="#/">Home</a> / Shop${cat?" / "+cat:""}</div><div class="shophead"><div><span class="eyebrow">GROCERIES</span><h1>${cat||brand||"All Products"}</h1><p>${list.length} products available</p></div><select onchange="shopSort(this.value)"><option value="">Sort by</option><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option><option value="rating">Top Rated</option></select></div><div class="filterlayout"><aside class="filters"><h3>Filters</h3><b>Category</b>${CATEGORIES.map(c=>`<label><input type="checkbox" ${cat===c.name?"checked":""} onchange="filterCategory('${c.name}')">${c.name}</label>`).join("")}<b>Brand</b>${BRANDS.map(b=>`<label><input type="checkbox" ${brand===b?"checked":""} onchange="filterBrand('${b}')">${b}</label>`).join("")}<b>Price</b><label><input type="radio" name="price" onchange="priceFilter(200)">Under ₹200</label><label><input type="radio" name="price" onchange="priceFilter(100)">Under ₹100</label><a href="#/shop" class="clear">Clear filters</a></aside><div><div class="mobileFilter"><input id="innerSearch" value="${q}" oninput="innerFilter(this.value)" placeholder="Search products..."></div><div id="shopGrid" class="products">${list.length?list.map(card).join(""):`<div class="empty"><h2>No products found</h2><a class="btn" href="#/shop">Clear search</a></div>`}</div></div></div></main>`);
}
function shopSort(v){let u=new URLSearchParams(location.hash.split("?")[1]||"");u.set("sort",v);location.hash="#/shop?"+u.toString()}
function filterCategory(c){location.hash="#/shop?cat="+encodeURIComponent(c)}
function filterBrand(b){location.hash="#/shop?brand="+encodeURIComponent(b)}
function priceFilter(max){let list=PRODUCTS.filter(p=>p.price<=max);$("#shopGrid").innerHTML=list.map(card).join("")}
function innerFilter(v){const q=v.toLowerCase();const list=PRODUCTS.filter(p=>(p.name+" "+p.cat+" "+p.brand).toLowerCase().includes(q));$("#shopGrid").innerHTML=list.map(card).join("")||`<div class="empty"><h2>No products found</h2></div>`}
function deals(){const list=[...PRODUCTS].sort((a,b)=>(1-b.price/b.old)-(1-a.price/a.old));shell(`<main class="page container"><div class="breadcrumb"><a href="#/">Home</a> / Deals</div><div class="dealhead"><div><span class="eyebrow">LIMITED TIME</span><h1>Deals of the Day</h1><p>Save more on everyday grocery essentials.</p></div><div class="dealclock"><b>Today's offers</b><span>Updated regularly</span></div></div><div class="products">${list.map(card).join("")}</div></main>`)}
function product(id){
 const p=productById(id);if(!p)return home();
 const related=PRODUCTS.filter(x=>x.cat===p.cat&&x.id!==p.id).slice(0,4);
 const s=left(id);
 shell(`<main class="page container"><div class="breadcrumb"><a href="#/">Home</a> / <a href="#/shop?cat=${encodeURIComponent(p.cat)}">${p.cat}</a> / ${p.name}</div><div class="productdetail"><div class="gallery"><div class="mainimage"><img id="mainProductImage" src="${p.img}" alt="${p.name}">${p.tag?`<span class="tag">${p.tag}</span>`:""}</div><div class="thumbs"><img src="${p.img}" onclick="swapImage(this.src)"><img src="${p.img}&sat=-10" onclick="swapImage(this.src)"><img src="${p.img}&blur=1" onclick="swapImage(this.src)"></div></div><div class="detailinfo"><span class="eyebrow">${p.cat} • ${p.brand}</span><h1>${p.name}</h1><div class="rating big">★ ${p.rating} <span>${p.reviews} reviews</span></div><div class="detailprice">${money(p.price)} <del>${money(p.old)}</del> <span>${Math.round((1-p.price/p.old)*100)}% OFF</span></div><p class="unit">${p.unit}</p><p>${p.desc}</p><div class="detailstock">${s<=0?'<b class="stock out">Out of stock</b>':s<=3?`<b class="stock low">Only ${s} left in stock</b>`:`<b class="stock ok">${s} units available</b>`}</div><div class="features"><span>${icon("check")} Fresh & quality checked</span><span>${icon("check")} Secure packaging</span><span>${icon("shield")} Easy checkout</span></div><div class="buyrow"><div class="qty"><button onclick="detailQty(-1)">−</button><b id="detailQty">1</b><button onclick="detailQty(1)">+</button></div><button class="btn ${s<=0?"disabled":""}" ${s<=0?"disabled":""} onclick="add(${p.id},Number($('#detailQty').textContent))">Add to cart</button><button class="roundwish ${inWish(p.id)?"selected":""}" onclick="toggleWish(${p.id})">${icon("heart")}</button></div><p class="deliverynote">${icon("truck")} Free delivery above ₹499 • Delivery fee ₹40 below threshold</p></div></div><section class="producttabs"><div><h2>Product information</h2><p>${p.desc} Product packaging, ingredients, nutrition and storage details should be checked on the physical package before use.</p></div><div><h2>Delivery information</h2><p>Choose a delivery slot at checkout. Availability depends on the delivery address in a production implementation.</p></div></section><section class="reviewsSection"><div class="reviewSummary"><div class="bigscore">${p.rating}</div><div><div class="stars">★★★★★</div><b>Based on ${p.reviews} reviews</b></div></div><div class="customerReviews"><div><div class="stars">★★★★★</div><p>Fresh and good quality. Arrived packed well.</p><b>Verified customer</b></div><div><div class="stars">★★★★☆</div><p>Good value and easy to order.</p><b>Verified customer</b></div></div></section></main>${productRow(related,"You may also like","Related products","#/shop?cat="+encodeURIComponent(p.cat))}`);
}
function swapImage(src){$("#mainProductImage").src=src}
function detailQty(d){const e=$("#detailQty");const max=left(location.hash.split("/")[2]);let n=Math.max(1,Math.min(Number(e.textContent)+d,left(max)));e.textContent=n}
function add(id,qty=1){
 const p=productById(id),s=left(id);qty=Math.max(1,Math.floor(qty));
 if(!p||s<=0){toast("This product is out of stock");return}
 const existing=cart.find(x=>x.id===id), current=existing?existing.qty:0;
 if(current+qty>s){toast(`Only ${s-current} more available`);return}
 existing?existing.qty+=qty:cart.push({id,qty});save();toast("Added to cart");render();
}
function toggleWish(id){id=Number(id);wishlist=inWish(id)?wishlist.filter(x=>x!==id):[...wishlist,id];save();toast(inWish(id)?"Added to wishlist":"Removed from wishlist");render()}
function cartPage(){
 const sub=subtotal(),need=Math.max(0,499-(sub-discount()));const percent=Math.min(100,sub/499*100);
 shell(`<main class="page container"><div class="breadcrumb"><a href="#/">Home</a> / Cart</div><h1>Shopping Cart</h1>${!cart.length?`<div class="empty panel"><div class="emptyicon">${icon("cart")}</div><h2>Your cart is empty</h2><p>Add fresh groceries to get started.</p><a class="btn" href="#/shop">Start shopping</a></div>`:`<div class="deliveryprogress panel">${need>0?`<b>${money(need)} more to get FREE DELIVERY</b>`:`<b>You've unlocked FREE DELIVERY</b>`}<div class="progress"><span style="width:${percent}%"></span></div></div><div class="cartlayout"><div class="panel"><div class="carttop"><b>${cartCount()} items</b><a href="#/shop">+ Add more items</a></div>${cart.map(x=>{const p=productById(x.id);return `<div class="cartrow"><img src="${p.img}" alt="${p.name}"><div class="cartname"><a href="#/product/${p.id}"><b>${p.name}</b></a><small>${p.brand} • ${p.unit}</small><span>${money(p.price)}</span><span class="stock ${left(p.id)<=3?"low":"ok"}">${left(p.id)} left in store</span></div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${x.qty}</b><button onclick="changeQty(${p.id},1)">+</button></div><b class="rowtotal">${money(p.price*x.qty)}</b><button class="remove" onclick="removeItem(${p.id})">${icon("close")}</button></div>`}).join("")}</div><aside class="panel summary"><h2>Order summary</h2><div><span>Subtotal</span><b>${money(sub)}</b></div><div><span>Delivery</span><b>${delivery()?"₹"+delivery():"FREE"}</b></div><div><span>Discount</span><b>-${money(discount())}</b></div><div class="couponbox"><input id="couponInput" value="${coupon}" placeholder="Coupon code"><button onclick="applyCoupon()">Apply</button></div>${coupon?`<small class="couponok">Coupon ${coupon} applied</small>`:""}<hr><div class="grand"><span>Total</span><b>${money(total())}</b></div><a class="btn full" href="#/checkout">Proceed to checkout</a><small>${icon("shield")} Secure checkout</small></aside></div>`}</main>`);
}
function applyCoupon(){const v=$("#couponInput").value.trim().toUpperCase();if(["FRESH100","SAVE50"].includes(v)){coupon=v;save();toast("Coupon applied")}else{coupon="";save();toast("Coupon not valid in this demo")}render()}
function changeQty(id,d){const x=cart.find(i=>i.id===id);if(!x)return;const next=x.qty+d;if(next>left(id)){toast(`Only ${left(id)} available`);return}if(next<=0)cart=cart.filter(i=>i.id!==id);else x.qty=next;save();render()}
function removeItem(id){cart=cart.filter(i=>i.id!==id);save();render()}
function wishlistPage(){const list=wishlist.map(productById).filter(Boolean);shell(`<main class="page container"><div class="breadcrumb"><a href="#/">Home</a> / Wishlist</div><div class="shophead"><div><span class="eyebrow">SAVED FOR LATER</span><h1>My Wishlist</h1><p>${list.length} saved products</p></div></div>${list.length?`<div class="products">${list.map(card).join("")}</div>`:`<div class="empty panel"><div class="emptyicon">${icon("heart")}</div><h2>Your wishlist is empty</h2><p>Save products here to find them quickly later.</p><a class="btn" href="#/shop">Browse products</a></div>`}</main>`)}
function checkout(){
 if(!cart.length){location.hash="#/cart";return}
 const saved=addresses[0]||{};
 shell(`<main class="page container"><div class="breadcrumb"><a href="#/">Home</a> / <a href="#/cart">Cart</a> / Checkout</div><h1>Checkout</h1><div class="steps"><span class="active">1 Address</span><span>2 Delivery</span><span>3 Payment</span><span>4 Review</span></div><div class="checkout"><div class="panel"><h2>Delivery address</h2><form id="checkoutForm" class="form" onsubmit="checkoutStep(event)"><div class="two"><input name="first" required value="${saved.first||""}" placeholder="First name"><input name="last" required value="${saved.last||""}" placeholder="Last name"></div><input name="phone" required value="${saved.phone||""}" pattern="[0-9]{10}" placeholder="10-digit mobile number"><input name="address" required value="${saved.address||""}" placeholder="House / Flat / Street"><div class="two"><input name="city" required value="${saved.city||""}" placeholder="City"><input name="pin" required value="${saved.pin||""}" pattern="[0-9]{6}" placeholder="PIN code"></div><textarea name="note" rows="3" placeholder="Delivery instructions (optional)"></textarea><h2>Delivery slot</h2><div class="slotgrid"><label><input type="radio" name="slot" value="2 PM – 4 PM" required>Today<br><b>2 PM – 4 PM</b></label><label><input type="radio" name="slot" value="4 PM – 6 PM">Today<br><b>4 PM – 6 PM</b></label><label><input type="radio" name="slot" value="6 PM – 8 PM">Today<br><b>6 PM – 8 PM</b></label></div><h2>Payment</h2><label class="pay"><input type="radio" name="pay" value="Cash on Delivery" required> Cash on Delivery</label><label class="pay"><input type="radio" name="pay" value="UPI"> UPI</label><label class="pay"><input type="radio" name="pay" value="Credit / Debit Card"> Credit / Debit Card</label><button class="btn full">Review & place order</button></form></div><aside class="panel summary"><h2>Your order</h2>${cart.map(x=>{const p=productById(x.id);return `<div class="summaryitem"><span>${p.name} × ${x.qty}</span><b>${money(p.price*x.qty)}</b></div>`}).join("")}<hr><div><span>Subtotal</span><b>${money(subtotal())}</b></div><div><span>Delivery</span><b>${delivery()?"₹"+delivery():"FREE"}</b></div><div><span>Discount</span><b>-${money(discount())}</b></div><div class="grand"><span>Total</span><b>${money(total())}</b></div></aside></div></main>`);
}
async function checkoutStep(e){e.preventDefault();const f=new FormData(e.target);const savedAddress={first:String(f.get("first")||"").trim(),last:String(f.get("last")||"").trim(),phone:String(f.get("phone")||"").trim(),address:String(f.get("address")||"").trim(),city:String(f.get("city")||"").trim(),pin:String(f.get("pin")||"").trim(),note:String(f.get("note")||"").trim(),slot:String(f.get("slot")||"")};
 if(API_ONLINE){try{const d=await apiFetch('/orders',{method:'POST',body:JSON.stringify({items:cart,discount:discount(),delivery:delivery(),slot:f.get('slot'),payment:f.get('pay'),address:savedAddress})});orders.unshift(d.order);addresses=addresses.length?addresses:[savedAddress];Object.entries(d.stock||{}).forEach(([k,v])=>stock[k]=v);cart=[];coupon='';save();toast('Order placed successfully');location.hash='#/success/'+d.order.id;return}catch(err){toast(err.message);return}}
 addresses=[savedAddress];save();toast("Address saved");const orderId="FC"+Math.floor(1000000+Math.random()*8999999);const items=cart.map(x=>({...x}));items.forEach(x=>stock[x.id]=Math.max(0,left(x.id)-x.qty));const o={id:orderId,date:new Date().toLocaleDateString("en-IN"),time:new Date().toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"}),items,total:total(),status:"Order Placed",slot:f.get("slot"),payment:f.get("pay"),address:savedAddress,history:[{status:"Order Placed",time:"Just now"},{status:"Order Confirmed",time:"Pending"},{status:"Packing",time:"Pending"},{status:"Out for Delivery",time:"Pending"},{status:"Delivered",time:"Pending"}]};orders.unshift(o);cart=[];coupon="";save();location.hash="#/success/"+orderId}

function ordersPage(){shell(`<main class="page container"><div class="breadcrumb"><a href="#/">Home</a> / Orders</div><div class="shophead"><div><span class="eyebrow">ORDER HISTORY</span><h1>My Orders</h1><p>Track your grocery purchases</p></div></div>${orders.length?orders.map(o=>`<div class="ordercard panel"><div><b>${o.id}</b><span>${o.date} • ${o.time}</span></div><div><b>${money(o.total)}</b><span>${o.items.reduce((s,x)=>s+x.qty,0)} items</span></div><span class="status">${o.status}</span><a class="btn smallbtn" href="#/track/${o.id}">Track order</a></div>`).join(""):`<div class="empty panel"><div class="emptyicon">${icon("truck")}</div><h2>No orders yet</h2><p>Your completed orders will appear here.</p><a class="btn" href="#/shop">Shop now</a></div>`}</main>`)}
function track(id){const o=orders.find(x=>x.id===id);if(!o)return ordersPage();shell(`<main class="page container"><div class="breadcrumb"><a href="#/">Home</a> / <a href="#/orders">Orders</a> / ${id}</div><div class="trackhead panel"><div><span class="eyebrow">ORDER TRACKING</span><h1>${id}</h1><p>${o.items.reduce((s,x)=>s+x.qty,0)} items • ${money(o.total)}</p></div><span class="status">${o.status}</span></div><div class="tracking panel">${o.history.map((h,i)=>`<div class="trackstep ${i===0?"current":""}"><div class="trackdot">${i===0?icon("check"):""}</div><div><b>${h.status}</b><span>${h.time}</span></div></div>`).join("")}</div><div class="trackinfo panel"><div><b>Delivery address</b><p>${o.address?.address}, ${o.address?.city} - ${o.address?.pin}</p></div><div><b>Delivery slot</b><p>${o.slot}</p></div><div><b>Payment</b><p>${o.payment}</p></div></div></main>`)}
function account(){if(!user)return auth();shell(`<main class="page container"><div class="breadcrumb"><a href="#/">Home</a> / Account</div><div class="accountgrid"><aside class="panel accountmenu"><div class="avatar">${user.name?.[0]?.toUpperCase()||"U"}</div><h2>${user.name}</h2><p>${user.email}</p><a class="active" href="#/account">Profile</a><a href="#/orders">My Orders</a><a href="#/wishlist">Wishlist</a><a href="#/addresses">Saved Addresses</a><button onclick="logout()">Logout</button></aside><section class="panel"><span class="eyebrow">MY ACCOUNT</span><h1>Profile</h1><p class="accountnote">Your profile and delivery data are connected to the FreshCart API when the server is running.</p><div class="profileform form"><label>Full name<input value="${user.name||""}" id="profileName" autocomplete="name"></label><label>Email<input value="${user.email||""}" id="profileEmail" type="email" autocomplete="email"></label><button class="btn" onclick="saveProfile()">Save changes</button></div><div class="quicklinks"><a href="#/addresses">${icon("pin")} Manage saved address</a><a href="#/checkout">${icon("truck")} Go to checkout</a></div></section></div></main>`)}
function auth(){shell(`<main class="authpage"><div class="authcard panel"><div class="authlogo">Fresh<span>Cart</span></div><div class="authswitch"><button id="loginTab" class="active" type="button" onclick="showLogin()">Login</button><button id="signupTab" type="button" onclick="showSignup()">Create account</button></div><div id="authbox"></div></div></main>`);showLogin()}
function showLogin(){const e=$("#authbox");$("#loginTab")?.classList.add("active");$("#signupTab")?.classList.remove("active");e.innerHTML=`<h1>Welcome back</h1><p>Sign in to manage orders, addresses and saved products.</p><form class="form" onsubmit="login(event)"><input name="email" type="email" required placeholder="Email address" autocomplete="email"><input name="password" type="password" required placeholder="Password" autocomplete="current-password"><button class="btn full" type="submit">Login</button></form><p class="authhint">New here? Click <b>Create account</b> above to register.</p>`}
function showSignup(){const e=$("#authbox");$("#signupTab")?.classList.add("active");$("#loginTab")?.classList.remove("active");e.innerHTML=`<h1>Create your account</h1><p>Register once and keep your profile, address and orders securely on the FreshCart API.</p><form class="form" onsubmit="signup(event)"><input name="name" required minlength="2" placeholder="Full name" autocomplete="name"><input name="email" type="email" required placeholder="Email address" autocomplete="email"><input name="password" type="password" required minlength="6" placeholder="Password (minimum 6 characters)" autocomplete="new-password"><input name="confirm" type="password" required minlength="6" placeholder="Confirm password" autocomplete="new-password"><button class="btn full" type="submit">Create account</button></form><p class="authhint">Your account is stored by the FreshCart API when the server is running.</p>`}
async function login(e){e.preventDefault();const f=new FormData(e.target);const email=String(f.get("email")||"").trim().toLowerCase();const password=String(f.get("password")||"");
 if(API_ONLINE){try{const d=await apiLogin(email,password);user=d.user;save();toast("Logged in successfully");location.hash="#/account";return}catch(err){toast(err.message);return}}
 const existing=accounts.find(a=>a.email===email);if(existing&&existing.password!==password){toast("Incorrect password");return}if(!existing){accounts.push({name:email.split("@")[0],email,password});}user={name:existing?.name||email.split("@")[0],email};save();toast("Logged in successfully");location.hash="#/account"}
async function signup(e){e.preventDefault();const f=new FormData(e.target);const name=String(f.get("name")||"").trim();const email=String(f.get("email")||"").trim().toLowerCase();const password=String(f.get("password")||"");const confirm=String(f.get("confirm")||"");if(password!==confirm){toast("Passwords do not match");return}
 if(API_ONLINE){try{const d=await apiSignup(name,email,password);user=d.user;save();toast("Account created successfully");location.hash="#/account";return}catch(err){toast(err.message);return}}
 if(accounts.some(a=>a.email===email)){toast("Account already exists. Please log in.");return}const account={name,email,password};accounts.push(account);user={name,email};save();toast("Account created successfully");location.hash="#/account"}
async function logout(){await apiLogout();user=null;addresses=[];orders=[];save();location.hash="#/";toast("Logged out")}
async function saveProfile(){const name=$("#profileName").value.trim(),email=$("#profileEmail").value.trim().toLowerCase();if(API_ONLINE){try{const d=await apiFetch('/me',{method:'PUT',body:JSON.stringify({name,email})});user=d.user;save();toast('Profile updated');render();return}catch(err){toast(err.message);return}}user.name=name;user.email=email;save();toast("Profile updated");render()}
function addressesPage(){const a=addresses[0]||{};shell(`<main class="page container"><div class="breadcrumb"><a href="#/">Home</a> / Addresses</div><div class="shophead"><div><span class="eyebrow">DELIVERY DETAILS</span><h1>Saved Addresses</h1><p>Save your delivery address once and reuse it at checkout.</p></div></div><div class="addresslayout"><section class="panel"><h2>${addresses[0]?"Edit saved address":"Add a delivery address"}</h2><form class="form" onsubmit="saveAddress(event)"><div class="two"><input name="first" required value="${a.first||""}" placeholder="First name" autocomplete="given-name"><input name="last" required value="${a.last||""}" placeholder="Last name" autocomplete="family-name"></div><input name="phone" required value="${a.phone||""}" pattern="[0-9]{10}" maxlength="10" placeholder="10-digit mobile number" autocomplete="tel"><input name="address" required value="${a.address||""}" placeholder="House / Flat / Street" autocomplete="street-address"><div class="two"><input name="city" required value="${a.city||""}" placeholder="City" autocomplete="address-level2"><input name="pin" required value="${a.pin||""}" pattern="[0-9]{6}" maxlength="6" placeholder="PIN code" autocomplete="postal-code"></div><textarea name="note" rows="3" placeholder="Delivery instructions (optional)">${a.note||""}</textarea><button class="btn full" type="submit">Save address</button></form></section><aside class="panel addresshelp"><div class="addressicon">${icon("pin")}</div><h2>Why save your address?</h2><p>It will automatically appear on checkout the next time you shop.</p><a href="#/checkout" class="btn outline">Continue to checkout</a></aside></div></main>`)}
async function saveAddress(e){e.preventDefault();const f=new FormData(e.target);const a={first:String(f.get("first")||"").trim(),last:String(f.get("last")||"").trim(),phone:String(f.get("phone")||"").trim(),address:String(f.get("address")||"").trim(),city:String(f.get("city")||"").trim(),pin:String(f.get("pin")||"").trim(),note:String(f.get("note")||"").trim()};
 if(API_ONLINE){try{const old=addresses[0];const d=old?.id?await apiFetch('/addresses/'+old.id,{method:'PUT',body:JSON.stringify(a)}):await apiFetch('/addresses',{method:'POST',body:JSON.stringify(a)});addresses=d.addresses||[d.address];save();toast('Address saved successfully');location.hash='#/addresses';return}catch(err){toast(err.message);return}}
 addresses=[a];save();toast("Address saved successfully");location.hash="#/addresses"}
function simple(title,html){shell(`<main class="page container"><div class="panel prose"><span class="eyebrow">FRESHCART</span><h1>${title}</h1>${html}</div></main>`)}
function subscribe(e){e.preventDefault();e.target.innerHTML=`<b>You're subscribed.</b>`;toast("Subscription saved")}
function admin(){
 const revenue=orders.reduce((s,o)=>s+o.total,0),low=PRODUCTS.filter(p=>left(p.id)<=3).length;
 shell(`<main class="page container"><div class="adminhead"><div><span class="eyebrow">STORE MANAGEMENT</span><h1>Admin Dashboard</h1><p>Front-end inventory and order management demo.</p></div><button class="btn" onclick="resetDemo()">Reset demo data</button></div><div class="stats"><div><span>Products</span><b>${PRODUCTS.length}</b></div><div><span>Orders</span><b>${orders.length}</b></div><div><span>Revenue</span><b>${money(revenue)}</b></div><div><span>Low stock</span><b>${low}</b></div></div><div class="adminlayout"><section class="panel"><h2>Inventory</h2><table class="adminTable"><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Status</th><th>Update</th></tr></thead><tbody>${PRODUCTS.map(p=>`<tr><td><div class="tableproduct"><img src="${p.img}"><span><b>${p.name}</b><small>${p.cat}</small></span></div></td><td>${money(p.price)}</td><td><input class="stockinput" id="stk${p.id}" type="number" min="0" value="${left(p.id)}"></td><td>${stockBadge(p)}</td><td><button class="tinybtn" onclick="updateStock(${p.id})">Save</button></td></tr>`).join("")}</tbody></table></section><section class="panel"><h2>Recent orders</h2>${orders.length?orders.slice(0,8).map(o=>`<div class="adminorder"><b>${o.id}</b><span>${money(o.total)}</span><small>${o.status}</small></div>`).join(""):`<p>No orders yet.</p>`}</section></div></main>`);
}
async function updateStock(id){const v=Math.max(0,Number($("#stk"+id).value)||0);if(API_ONLINE){try{const d=await apiFetch('/admin/products/'+id+'/stock',{method:'PATCH',body:JSON.stringify({stock:v})});stock[id]=d.product.stock;save();toast('Stock updated');render();return}catch(err){toast(err.message);return}}stock[id]=v;save();toast("Stock updated");render()}
function resetDemo(){if(confirm("Reset cart, wishlist, orders, account and stock?")){localStorage.clear();location.reload()}}
function faq(){simple("Frequently Asked Questions",`<h3>How does delivery work?</h3><p>Choose an address and delivery slot at checkout. In a production version, slots would be calculated from your delivery area.</p><h3>When is delivery free?</h3><p>This demo gives free delivery for orders of ₹499 or more after discounts.</p><h3>How does stock work?</h3><p>Each product starts with 10 units. Adding items reduces the available quantity in the cart view; placing an order deducts purchased units from inventory.</p><h3>Can I use coupons?</h3><p>Try <b>FRESH100</b> on orders above ₹499 or <b>SAVE50</b> on orders above ₹299.</p>`)}
function router(){
 const h=location.hash||"#/";
 if(h==="#/"||h==="#")home();
 else if(h==="#/shop"||h.startsWith("#/shop?"))shop();
 else if(h==="#/deals")deals();
 else if(h.startsWith("#/product/"))product(h.split("/")[2]);
 else if(h==="#/cart")cartPage();
 else if(h==="#/wishlist")wishlistPage();
 else if(h==="#/checkout")checkout();
 else if(h.startsWith("#/success/"))success(h.split("/")[2]);
 else if(h==="#/orders")ordersPage();
 else if(h.startsWith("#/track/"))track(h.split("/")[2]);
 else if(h==="#/account")account();
 else if(h==="#/addresses")addressesPage();
 else if(h==="#/faq")faq();
 else if(h==="#/contact")simple("Contact Us",`<p>Our support team is available every day from 8 AM to 10 PM.</p><div class="contactgrid"><div>${icon("phone")}<b>1800-000-000</b><span>Customer support</span></div><div>${icon("mail")}<b>support@freshcart.example</b><span>Email support</span></div></div>`);
 else if(h==="#/shipping")simple("Shipping Policy",`<p>Delivery availability and fees depend on the delivery address. This demo uses free delivery at ₹499+ and ₹40 below that threshold.</p><p>Replace this sample policy with your actual delivery zones, time windows and service commitments before publishing.</p>`);
 else if(h==="#/returns")simple("Refund & Return Policy",`<p>Replace this demo policy with your business's actual return, replacement, refund and damaged-product rules before launch.</p>`);
 else if(h==="#/privacy")simple("Privacy Policy",`<p>This front-end demo stores cart, wishlist, order and account information in your browser's LocalStorage. A production website should use a secure backend and publish a complete privacy policy.</p>`);
 else if(h==="#/terms")simple("Terms & Conditions",`<p>This website is a front-end demonstration template. Replace sample terms, prices, inventory, delivery areas and business details before publishing.</p>`);
 else if(h==="#/admin")admin();
 else home();
}
function render(){router()}
function toast(t){const e=document.createElement("div");e.className="toast";e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),1800)}
window.addEventListener("hashchange",router);router(); apiSync();